export enum SKComparator {
  LESS_OR_EQUAL_THAN = "LESS_OR_EQUAL_THAN",
  LESS_THAN = "LESS_THAN",
  MORE_OR_EQUAL_THAN = "MORE_OR_EQUAL_THAN",
  MORE_THAN = "MORE_THAN",
  BETWEEN = "BETWEEN",
  BEGINS_WITH = "BEGINS_WITH",
}
